backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

  # This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - label: "Pages"
    name: "data"
    files:
      - label: "Hero Section"
        name: "hero"
        file: "index.html"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
