backend:
 name: git-gateway
 branch: master # Branch to update (optional; defaults to master)

  # This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "assets/images" # Media files will be stored in the repo under images/uploads


collections:
 - label: "Pages"
   name: "pages"
   files:
    - label: "Home"
      name: "home"
      file: "index.html"
      fields:
        - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'default'}
        - {label: 'Heading', name: 'hero-heading', widget: 'string'}
        - {label: 'Content', name: 'hero-content', widget: 'string'}
 - name: 'sections'
   label: 'Sections'
   files: 
    - label: 'About Section'
      name: 'about'
      file: '_data/about.yml'
      fields: 
       - label: 'About Items'
         name: 'items'
         widget: 'list'
         fields: 
           - {label: 'Heading', name: 'heading', widget: string}
           - {label: 'Description', name: 'desc', widget: string}
           - {label: 'Image', name: 'img', widget: image}
           - {label: 'Image Alt Text', name: 'alt', widget: string}
    - label: 'How it Works Section'
      name: 'how it works'
      file: '_data/how-it-works.yml'
      fields: 
       - label: 'How it Works Items'
         name: 'items'
         widget: 'list'
         fields: 
          - {label: 'Image', name: 'img', widget: image}
          - {label: 'Heading', name: 'heading', widget: string}
          - {label: 'Description', name: 'desc', widget: string}
    - label: 'Resources Section'
      name: 'resources'
      file: '_data/resources.yml'
      fields: 
       - label: 'Resources'
         name: 'items'
         widget: 'list'
         fields: 
          - {label: 'Icon', name: 'icon', widget: image}
          - {label: 'Name', name: 'name', widget: string}
          - {label: 'Info', name: 'info', widget: string}
          - {label: 'Link', name: 'link', widget: string}